[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "Ubuntu Mono"

[window]
decorations = "buttonless"
startup_mode = "Maximized"

[window.padding]
x = 8
y = 8
