[general]
import = [
    "~/.dotfiles/alacritty/github_light.toml"
]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 15

[font.normal]
family = "Ubuntu Mono"

[window]
decorations = "Buttonless"
startup_mode = "Maximized"
dynamic_padding = true
opacity = 1

[window.padding]
x = 16
y = 16

[[hints.enabled]]
mouse.enabled = true
command = "open"
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
hyperlinks = true

[cursor]
thickness = 0.3
blink_interval = 200
