[general]
import = [
    "~/.dotfiles/alacritty/github_dark_dimmed.toml"
]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]

size = 13

[font.normal]
family = "0xProto Nerd Font"

[window]
decorations = "Buttonless"
startup_mode = "Maximized"
dynamic_padding = true
opacity = 1
option_as_alt = "Both"

[window.padding]
x = 10
y = 10

[[hints.enabled]]
mouse.enabled = true
command = "open"
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
hyperlinks = true

[cursor]
thickness = 0.3
blink_interval = 200

[cursor.style]
blinking = "Always"
shape = "Block"

[font.glyph_offset]
x = 0
y = 0

#[font.normal]
#family = "Hack Nerd Font"
#style = "Regular"

[scrolling]
history = 15000


[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b\r"

